// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A style recommendation AI agent.
 *
 * - recommendStyle - A function that handles the style recommendation process.
 * - StyleRecommendationInput - The input type for the recommendStyle function.
 * - StyleRecommendationOutput - The return type for the recommendStyle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StyleRecommendationInputSchema = z.object({
  occasion: z.string().describe('The occasion for which the outfit is needed (e.g., office, party, casual).'),
  colorPreference: z.string().describe('The preferred color of the outfit.'),
  bodyType: z.string().describe('The user\u0027s body type (e.g., pear-shaped, apple-shaped, hourglass).'),
  stylePreference: z.string().describe('The user\u0027s preferred style (e.g., modern, elegant, avant-garde).'),
});

export type StyleRecommendationInput = z.infer<typeof StyleRecommendationInputSchema>;

const StyleRecommendationOutputSchema = z.object({
  recommendation: z.string().describe('The recommended outfit pairing based on the user\u0027s preferences.'),
  reasoning: z.string().describe('The reasoning behind the outfit recommendation.'),
});

export type StyleRecommendationOutput = z.infer<typeof StyleRecommendationOutputSchema>;

export async function recommendStyle(input: StyleRecommendationInput): Promise<StyleRecommendationOutput> {
  return recommendStyleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'styleRecommendationPrompt',
  input: {schema: StyleRecommendationInputSchema},
  output: {schema: StyleRecommendationOutputSchema},
  prompt: `You are a personal fashion stylist for Indian women, specializing in western officewear.

  A user is requesting outfit recommendations.  Consider their occasion, color preferences, body type, and style when making the recommendation.

  Occasion: {{{occasion}}}
  Color Preference: {{{colorPreference}}}
  Body Type: {{{bodyType}}}
  Style Preference: {{{stylePreference}}}

  Recommend an outfit, and explain why it matches their preferences.`,
});

const recommendStyleFlow = ai.defineFlow(
  {
    name: 'recommendStyleFlow',
    inputSchema: StyleRecommendationInputSchema,
    outputSchema: StyleRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
